builders:
  rohd_builder:
    import: "package:rohd/builder.dart"
    builder_factories: ["rohdBuilder"]
    build_extensions: {".dart": [".rohd_builder.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]

targets:
  $default:
    sources:
      - $package$
      - lib/**
      - test/**
      - example/**
    builders:
      rohd|rohd_builder:
        generate_for:
          - $package$
          - lib/**
          - test/**
          - example/**
        enabled: true
      source_gen|combining_builder:
        enabled: true
        options:
          ignore_for_file:
            - avoid_setters_without_getters
            - unused_element_parameter
            - unnecessary_this
            - lines_longer_than_80_chars