builders:
  rohd_builder:
    import: "package:rohd/builder.dart"
    builder_factories: ["RohdBuilder"]
    build_extensions: {".dart": [".rohd.dart"]}
    auto_apply: dependents
    build_to: source
    default_build_mode: release