name: rohd
version: 0.6.6
description: The Rapid Open Hardware Development (ROHD) framework, a framework for describing and verifying hardware.
homepage: https://intel.github.io/rohd-website
repository: https://github.com/intel/rohd
issue_tracker: https://github.com/intel/rohd/issues
documentation: https://intel.github.io/rohd-website/docs/sample-example/

environment:
  sdk: '>=3.0.0 <4.0.0'

# TODO split out builder into a separate package

dependencies:
  analyzer: ^8.0.0
  build: ^3.0.0
  collection: ^1.15.0
  logging: ^1.0.1
  meta: ^1.3.0
  source_gen: ^4.0.0
  test: ^1.17.3

dev_dependencies:
  benchmark_harness: ^2.2.0
  build_runner: ^2.4.11
  yaml: ^3.1.1
